### ISSUE TITLE
Context Menu on Label/Button is not shown

### ISSUE THREAD

**Issue by BjBe82** [eclipse-sprotty/sprotty#345] opened 2023-02-22 10:39 UTC
Last working Version: 0.12.0
Bugged Version: 0.13.0

The context menu is no longer triggered (IContextMenuService is not called) if the user right-clicks a label (or button). For smaller nodes where the label covers most of the node, this makes it nearly impossible to open the context menu.

**Comment by dhuebner** [comment] 2023-02-23 13:17
@BjBe82 
> Last working Version: 0.12.0
> Bugged Version: 0.12.0

Do you mean "Bugged Version: 0.13.0"?

**Comment by dhuebner** [comment] 2023-02-23 13:33
Probably caused by https://github.com/eclipse-sprotty/sprotty/pull/316

**Comment by BjBe82** [comment] 2023-02-23 13:36
Yes, I meant 0.13.0 -> update the ticket.

**Comment by dhuebner** [comment] 2023-02-23 14:47
@BjBe82 
I don't really understand the expected behavior looking into the current implementation. I'm about to create a reproducible example in one of our example projects to understand what and when should happen. But I think the `isSelectable(target)` is what prevents your app to show a context menu. 
https://github.com/eclipse-sprotty/sprotty/blob/master/packages/sprotty/src/features/context-menu/mouse-listener.ts#L60

**Comment by dhuebner** [comment] 2023-02-24 13:33
@BjBe82 
You can try the current development state in the class diagram example here: https://gitpod.io/#https://github.com/eclipse-sprotty/sprotty/pull/346
Note that the node label itself is not selectable.

Feedback regarding the right-click selection behavior is very welcome here  #346

**Comment by spoenemann** [comment] 2023-11-02 11:49
Shall this be kept open, or is it fixed with #346?

**Comment by dhuebner** [comment] 2023-11-02 13:54
@spoenemann 
I think it is fixed now. Probably just forgot to close it

**Closed by dhuebner** 2023-11-02 13:54 UTC
Labels: bug

**Comment by BjBe82** [comment] 2023-11-03 10:50
Sorry for the late reply, I checked this with version 1.0.0 today and can confirm that it is fixed.
